### ISSUE TITLE
Эндпоинт take_book 

### ISSUE THREAD

**Issue by KatantDev** [FarPostBooks/farpostbooks_backend#10]
Одну и ту же книгу можно взять несколько раз. 

Какой из путей развития используем (желательно уточнить у заказчика):
1. Оставляем как есть (несколько записей взятия книги одним юзером)
2. При попытке взять книгу второй раз - запрещаем её взять
3. При попытке взять книгу перезаписываем в старой записи время, когда книга была взята
4. При попытке взять книгу оставляем в старой записи время, когда книга была взята, но удаляем время когда была возвращена.

**Comment by strwatcher** [comment]
1. Норм вариант, он отражает историю полноценно, не может быть никаких коллизий

2. Норм, но как-будто ограничение бессмысленное

3. Будет ломать таймлан

4. Если записи идут подряд хороший вариант, но и только

Предлагаю объединить 1 и 4

- Если юзер берет книгу и прошлый раз её брал он же, то запись мержится
- Иначе, разные записи

Или оставить только 1, потому что она наиболее точно отражает действительность.

**Comment by Faner201** [comment]
Самый лучший вариант, это первый. Второй не очень, ведь какое то ограничение, которое не нужно появляется. Соглашусь с Мишей по поводу третьего варианта. Четвёртый вариант так же поломает логику времени у записей.

**Comment by KatantDev** [comment]
Согласовал issue с заказчиком
![64858E31-6841-4DD7-BEB8-66EB5D062A22](https://user-images.githubusercontent.com/34680896/220016546-d6ac553f-0047-4e9d-a803-d6d6daabbe34.jpeg)
